mayflower/nixexprs

monitoring/default.nix

- removes implicit SSH TCP blackbox checks

monitoring: refactor prometheus scrape config generation

---

monitoring/alert-rules.nix

alert-rules: add rules for deployment state check

---

monitoring/blackbox-exporter.nix
monitoring/default.nix

https://github.com/NixOS/nixpkgs/pull/36909

monitoring: switch to new prometheus exporters module

---

monitoring/default.nix

enables the `prometheus-{postfix,dovecot}-exporter` on hosts that have `postfix` or `dovecot` enabled

montoring: enable dovecot and postfix exporters by default

---

monitoring/default.nix

All specified `extraScrapeConfigs` will be scraped by the prometheus
instances which are in the same datacenter as the target host.

monitoring: add extraScrapeConfigs option

---

module-list.nix
modules/automx.nix
modules/base.nix
pkgs/python-packages.nix
pkgs/python/automx/default.nix

Init automx

---

pkgs/service-overview/demo.nix
pkgs/service-overview/templates/entry.nix

- adds support for service names that contain spaces
- adds demo expression for testing

pkgs/service-overview: support spaces in service names, add demo expression

---

module-list.nix
modules/router.nix

I had pushed it unintentionally once, properly include it and import recent changes.
Plese merge, DO NOT REBASE.

Finish including router module

---

hydra-jobs/packages.nix

hydra-jobs: build ghc

---

hydra-jobs/jobsets.nix

Branch was merged into master.

remove job hydra-jobs-1809

---

overlay.nix

Needed to connect to PrivacyIDEA,

overlay: build freeradius with rest plugin

---

pkgs/mailman/default.nix
pkgs/mailman/hyperkitty.nix
pkgs/mailman/postorius-allow-empty-emailtemplate.patch
pkgs/mailman/postorius.nix
pkgs/mailman/users_can_create_lists.patch
pkgs/python/django-q/default.nix
pkgs/python/mailmanclient/default.nix

Please don't rebase, hash is used in deployment MR

Mailman bump

---

modules/mailman3.nix

Explicitly specify API URL for template fetching

---

overlay.nix
pkgs/conversejs.nix

adds the XMPP web client with OMEMO support (to replace kaiwa)

pkgs: add conversejs

---

pkgs/conversejs.nix

bump to [latest version](https://github.com/conversejs/converse.js/releases/tag/v4.1.1)

conversejs: 4.1.0 -> 4.1.1

---

modules/base.nix

too often unreachable/tls errors

modules/base: remove cache.nixos.community

---

modules/monitoring/alert-rules.nix

modules/monitoring: don't page node_deployed

---

.gitignore
module-list.nix
modules/simplesamlphp.nix
overlay.nix
pkgs/simplesamlphp/default.nix
pkgs/simplesamlphp/module-privacyidea.nix

simpleSAMLphp module

---

module-list.nix
modules/matrix.nix

Inspired from https://gitlab.com/hschaeidt/nixos-matrix

add matrix module

---

modules/matrix.nix

matrix: add mayflower.matrix.riot.extraConfig

---

module-list.nix
modules/cachet.nix
overlay.nix
pkgs/cachet/composer-env.nix
pkgs/cachet/default.nix
pkgs/cachet/override.nix
pkgs/cachet/php-packages.nix

purely copy pasta from svanderburg/composer2nix generated nix code
builds
Change as you see fit, this is just pushed to save time for others

WIP: add cachet package

---

overlay.nix

overlay: temporarily use loki master

---

modules/mailman3.nix

please merge with merge commit

modules/mailman3: add service to whitelist mailman submissions

---

modules/mailman3.nix

modules/mailman3: don't filter anything coming from localhost

---

modules/matrix.nix

matrix: fix for current 19.09

---

modules/matrix.nix
overlay.nix

switched from mxisd to ma1sd and updated riot-web config

matrix updates

---

hydra-jobs/jobsets.nix
hydra-jobs/spec.json

hydra: remove hydra nixexprs branch pinning

---

modules/monitoring/alert-rules.nix

monitoring: alert on inodes

---

modules/monitoring/default.nix

depends on node_exporter 1.x. see https://github.com/mayflower/nixpkgs/pull/83

make certain node collectors dependant on node config

---

hydra-jobs/packages.nix

I don't think we need it, and it's failing to build %)

hydra-jobs: remove cufflinks

---

modules/demockrazy.nix

This reverts commit 1241e11b13b535d2f295594e631c659e674a3dcd.
cc @lheckemann @WilliButz

Revert "modules/demockrazy: supply django secret key as file"

---

pkgs/cachet/0001-Improve-slack-notifications.patch
pkgs/cachet/php-packages.nix

update cachet, dependencies and slack-patch

cachet: update

---

modules/base.nix

configure nginx access logs on a per node / per vhost / etc basis

base: allow for selective nginx access logging

---

hydra-jobs/packages.nix
modules/monitoring/default.nix

related to the switch from the unmaintained kumina exporter to the new exporter available from upstream nixpkgs

Switch unbound exporter

---

modules/matrix.nix
overlay.nix

This way, hydra will build it. Also reenable the tests, which work now.

matrix: move synapse override to overlay

---

module-list.nix
modules/copy-nixpkgs.nix
modules/secrets.nix

Add copy-nixpkgs module

---

modules/cachet.nix
pkgs/cachet/composer-env.nix
pkgs/cachet/composer.json
pkgs/cachet/composer.lock
pkgs/cachet/default.nix
pkgs/cachet/php-packages.nix

cachet: bump to support php 8

---

modules/simplesamlphp.nix
pkgs/simplesamlphp/default.nix
pkgs/simplesamlphp/module-privacyidea.nix

Our custom theme was slightly broken already, so we'll just switch back
to the upstream default for now.

modules/simplesamlphp: remove custom theming support, update packages

---

hydra-jobs/packages.nix
overlay.nix

See message of 9850fee for further details.

Update matrix-synapse oidc patch

---

overlay.nix

included in 1.91.0: https://github.com/matrix-org/synapse/commit/d6ae4041a4c014a8c234f1afccc80867bf5b7df0

overlay: drop patch for matrix-synapse, included in latest release

---

hydra-jobs/default.nix
hydra-jobs/jobsets.nix

To check if everything is still fine w/o structured attrs.

hydra-jobs: jobsets to build new branch with __structuredAttrs = false

---

modules/log-aggregation.nix

The resulting configuration is functionally equivalent, but now uses [aws_storage_config](https://grafana.com/docs/loki/latest/configure/#aws_storage_config) instead of [s3_storage_config](https://grafana.com/docs/loki/latest/configure/#s3_storage_config) because the latter is not available when using [named_stores](https://grafana.com/docs/loki/latest/configure/#named_stores_config). This change should make it possible to extend the module's loki configuration with additional storage configurations, also making a transition from minio to garage easier.

modules/log-aggregation: switch from yaml to nix, use named_stores

---

modules/monitoring/default.nix
modules/monitoring/snmp-exporter.nix
overlay.nix
pkgs/prometheus-snmp-exporter-generator.nix

also more options for generator in modules/monitoring/snmp-exporter.nix

snmp-exporter: 0.21.0 -> 0.24.1 librenms 1.67 -> 23.10.0
