mayflower/nixexprs

- base.nix
Enables the systemd-timer for the `docker-prune` service. It runs `weekly` by default.
> base: enable docker system prune timer

- monitoring/default.nix
The filesystem collector requires a target directory to be passed.
> monitoring: add missing path for node-filesystem-collector

- monitoring/default.nix
The group set in [nixos/prometheus-postfix-exporter: set default group](https://github.com/mayflower/nixpkgs/pull/64) is allowed to access the journal, so setting it here is not needed anymore.
> monitoring: use default group for postfix-exporter

- modules/monitoring/default.nix
Enables the [rspamd exporter](https://github.com/mayflower/nixpkgs/pull/69) and the corresponding scrape-jobs by default when rspamd is enabled.
> modules/monitoring: monitor rspamd hosts

- pkgs/service-overview/default.nix
- pkgs/service-overview/templates/entry.nix
- services are now sorted by status
- adds the status `external` for SaaS and similar
> pkgs/service-overview: sort by status & add status external

- modules/base.nix
This can and should be done per host, remove this legacy.
Please merge, don't rebase, as referenced by hash.
> modules/base: disallow unfree

- hydra-jobs/packages.nix
adds `cabal-install` and `haskellPackages.hoogle` to hydra jobs
> hydra-jobs: build cabal-install & hoogle

- modules/monitoring/alert-rules.nix
Triggers false alerts when using docker.
> monitoring: ignore nsfs mounts in alerting rules

- overlay.nix
This adds a patch to oxidized so that the current system time stamp is excluded from tp-link configs.
> oxidized: add patch to exclude tplink timestamp

- modules/monitoring/alert-rules.nix
This makes predictions more precise and therefore produces less false positives.
A possible, undesirable situation would be, that a host's drives fill up
very slowly just below 90%. This would not cause an alert, so there is now
an additional threshold at 80% where an alert gets triggered.
> monitoring/alert-rules: improve filesystem_full alerts

- overlay.nix
this is much more trivial than backporting all needed node-related changes
> overlay: use upstream matrix-appservice-slack

- modules/monitoring/alert-rules.nix
Only alert on predictions if the underlying time series is still relevant.
> monitoring/alert-rules: fix alerts with predictions

- modules/monitoring/default.nix
- explicitly enable collectors, don't rely on default collectors
- for containers, disable collectors which yield duplicate
metrics with the host
replaces #108
> monitoring: refactor how and which node-collectors are enabled

- modules/monitoring/default.nix
In node_exporter 1.x, it seems the collector is no longer enabled by only specifying the directory.
> monitoring: actually enable textfile collector

- modules/simplesamlphp.nix
Now that I'm running a setup with simplesamlphp in my personal infrastructure, I started using this fairly helpful module and decided to contribute back a few improvements.
The summaries of the commits are in the collapsible sections below:
<details>
<summary>modules/simplesamlphp: don't use an empty string as cookie default </summary>
When I initially deployed simplesamlphp to my server with leaving
`phpSessionCookieName` and `authTokenCookieName` empty (i.e. unspecified),
I got the following slightly confusing error in my logs when trying to
authenticate as `admin`:
ERR [d5422ef7b1] Cannot set authentication token cookie: Headers already sent
The reason is actually kinda weird: SimpleSAMLPHP tries to set a cookie
using PHP's `setcookie()`-function[1]. The docs state that `false` is …
> modules/simplesamlphp: misc improvements

- modules/simplesamlphp.nix
To quote the NixOS 21.05 "Okapi" release-notes:
> When defining a new user, one of users.users.<name>.isNormalUser and
> users.users.<name>.isSystemUser is now required
Since no default is set, this means that evaluating the
`simplesamlphp`-module on NixOS 21.05 fails with an assertion error.
This is not a breaking change since the user already has a fixed UID
allocated on existing systems, on new systems the UID will be <999 (on
my server it has `1003` for instance).
> modules/simplesamlphp: fix eval for 21.05

- modules/monitoring/alert-rules.nix
Also a more aggressive threshold.
> alert rules: only fire high-latency alert when host is up

- pkgs/simplesamlphp/default.nix
The full change-logs can be found on the vendor's homepage[1]. The
reason for the update is that there were a few minor security advisories
disclosed that affect our current version[2]. None of them seemed easily
exploitable, but since this is a rather sensitive piece of software, an
update is still a good idea.
I successfully deployed this to my own systems and tested a login via
`u2f` and `yubico-otp` for Nextcloud and `wiki-js`. No adjustment of my
existing configuration was necessary for this.
I left out an update of the module for PrivacyIDEA[3] on purpose because
I encountered some issues with `u2f`-auth then. I already filed a bug-report
for this[4].
[1] https://simplesamlphp.org/docs/stable/simplesamlphp-changelog
[2] https://simplesamlphp.org/security
[3] …
> simplesamlphp: 1.17.2 -> 1.19.1

- modules/simplesamlphp.nix
On NixOS 21.11 `pkgs.php` points to PHP 8.0 by default, however this
doesn't work with `simplesamlphp`.
> modules/simplesamlphp: pin PHP to 7.4

- modules/monitoring/alert-rules.nix
max isn't a "dangerous" threshold, only the point from which cooling
should be used at capacity.
Also, multiplying temperatures (except °K) is very silly.
> monitoring: only alert when close to critical temperature

- modules/matrix.nix
See https://matrix-org.github.io/synapse/latest/upgrade.html#dropping-support-for-webclient-listeners-and-non-https-web_client_location
> modules/matrix: remove webclient

- modules/matrix.nix
Needed to properly deactivate a user. Without this being enabled, the
`deactivate`-call fails with the following error:
Request POST http://matrix.mayflower.de/_matrix/identity/api/v1/3pid/unbind - Error M_NOT_AVAILABLE: This action is currently not available. Contact your administrator to enable it.
> modules/matrix: enable `unbind` in `ma1sd`

- modules/monitoring/default.nix
Note: this assumes `localhost:11334` (the rspamd http server) to be
exposed via `https://hostname/rspamd` on the mailserver.
Port 80 will be automatically upgraded to 443 when using
`forceSSL = true;` (which is true in our case).
> modules/monitoring: use builtin exporter for rspamd

- flake.nix
* Add a description.
* Fix evaluation (`outputs` must be a function rather than a list).
* It is a convention to expose `nixosModules` as attr-set rather than as
list. To retain backwards-compat with e.g. our deployment, I decided
to keep the `module-list.nix` and added a simple expression which
generates attribute-names for modules like this:
* `modules/simplesamlphp.nix` -> `nixosModules.mf-simplesamlphp`
* `modules/monitoring/default.nix` -> `nixosModules.mf-monitoring`
There's no support for deeper nesting because it simply isn't needed,
but it should be rather trivial to implement.
> flake.nix: Fix

- modules/simplesamlphp.nix
The modules aren't created anymore, thus the `rm` fails like this:
privacyidea-muc......> rm: cannot remove '/run/simplesamlphp/modules/mayflower': No such file or directory
privacyidea-muc......> Activation script snippet 'simplesamlphp' failed (1)
Small oversight from 7799ded8d37b57101cf277ad3d4f69d9f58d9d6c, but with
a low impact because the rest of the activation correctly ran through
and no service was negatively impacted on the machine.
> modules/simplesamlphp: drop obsolete `rm` statement from activation script

- hydra-jobs/packages.nix
- overlay.nix
To build the overridden git pkg introduced in upstream
gitlab-workhorse service module
https://github.com/NixOS/nixpkgs/blob/mf-next/nixos/modules/services/misc/gitlab.nix#L16
Since my system does not build this git version because of some
compound key folder names tests failing
https://public-inbox.org/git/?q=t0021+t3910 and hydra does not know
about this packaged git version, i explicitly add it here.
> hydra-jobs: add temporary gitlab-workhorse-git-2-35-4

- overlay.nix
- pkgs/python-packages.nix
meh, python3 override does not override python39Packages it seems,
and documentation for disabledTests attribute is not valid for this pkg.
> pytest-xdist: dontCheck on aarch64-linux

- modules/monitoring/alert-rules.nix
This change makes it obvious whether the number of active silences increased or decreased, rather than just indicating that it changed.
> monitoring/alert-rules: improve alerts_silences_changed

- modules/matrix.nix
Wasn't a noticeable issue so far and the [manual](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html?highlight=bind_add#listeners) is not making this very obvious but now the service listens on both ipv4 and ipv6
> modules/matrix: fix federation not using IPv6 by default

- modules/matrix.nix
- overlay.nix
* Drop password provider which is now obsolete.
* Apply patch from matrix-org/synapse to be able to specify `client_secret_file` rather than `client_secret` in the OIDC section.
* Also expose `/_synapse/client` from the http listener via nginx. This endpoint is needed for the OIDC callback[1].
[1] https://goauthentik.io/integrations/services/matrix-synapse/
> modules/matrix: prepare for authentik migration
